
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.io.FileInputStream;
import java.lang.*;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author umer
 */
public class MedicalStore extends javax.swing.JFrame {

    /**
     * Creates new form MedicalStore
     * 
     */
   
    DefaultTableModel updateTableModel;
    DefaultTableModel deleteTableModel;
    DatabaseManager dbm=new DatabaseManager();
    Validation valid=new Validation();
    Item items=new Item(dbm.getAllMedicines());
    
    public MedicalStore() {
        this.setUndecorated(true);//removes the title bar
        //this.setAlwaysOnTop(true);//this interface will be always on top
        this.setResizable(false);//not resizeable now
        this.setVisible(true);
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();//this get the sizes of screen
        int xsize = (int) tk.getScreenSize().getWidth();//taking the width of screen
        int ysize = (int) tk.getScreenSize().getHeight();//taking the height of screen
        this.setSize(xsize, ysize);
    }
    
    public void initUpdateTable()
    {
        updateTableModel=new DefaultTableModel(0,0);
        updateTableModel.addColumn("Product Id");
        updateTableModel.addColumn("Product Name");
        updateTableModel.addColumn("Company Name");
        updateTableModel.addColumn("Product Category");
        updateTableModel.addColumn("Quantity");
        updateTableModel.addColumn("Price Per Unit");
    }
    
    public void initDeleteTable()
    {
        deleteTableModel=new DefaultTableModel(0,0);
        deleteTableModel.addColumn("Product Id");
        deleteTableModel.addColumn("Product Name");
        deleteTableModel.addColumn("Company Name");
        deleteTableModel.addColumn("Product Category");
        deleteTableModel.addColumn("Quantity");
        deleteTableModel.addColumn("Price Per Unit");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jBMedicine = new javax.swing.JButton();
        jBCompanies = new javax.swing.JButton();
        jBSalesRecords = new javax.swing.JButton();
        jBNewSales = new javax.swing.JButton();
        jBChangePassword = new javax.swing.JButton();
        jBLogOut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTSearch = new javax.swing.JTextField();
        jBSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jlNameLog = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        MedicinePanel = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jBBackMedicinePanel = new javax.swing.JButton();
        jBIMedicine = new javax.swing.JButton();
        jBUpdateMedicine = new javax.swing.JButton();
        jBDeleteMedicine = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDeleteTable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        INVALIDINPUT = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        MedicineInput = new javax.swing.JFrame();
        jPanel6 = new javax.swing.JPanel();
        jBMedicineInputBack = new javax.swing.JButton();
        jBMedicineInputInsert = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTProductName = new javax.swing.JTextField();
        CompanyChioce = new java.awt.Choice();
        ProductChoice = new java.awt.Choice();
        jTProductPrice = new javax.swing.JTextField();
        jTProductQuantity = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        UpdateMedicinePanel = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jBBackUpdateMedicine = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblUpdateTable = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        UpdateMedicineNames = new java.awt.Choice();
        jTUpdatePrice = new javax.swing.JTextField();
        jBUpdatePrice = new javax.swing.JButton();
        jTUpdateQuantity = new javax.swing.JTextField();
        jBUpdateQuantity = new javax.swing.JButton();
        InsertCompany = new javax.swing.JFrame();
        jPanel7 = new javax.swing.JPanel();
        jBCompanyInputBack = new javax.swing.JButton();
        jBCompanyInputInsert = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTCompanyName = new javax.swing.JTextField();
        jTComapnyContact = new javax.swing.JTextField();
        jTComapnyAddress = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        JTCompanyCountry = new javax.swing.JTextField();
        jTCompanyEmail = new javax.swing.JTextField();
        ComapnyPanel = new javax.swing.JFrame();
        jPanel11 = new javax.swing.JPanel();
        jBBackCompanyPanel = new javax.swing.JButton();
        jBInsertCompany = new javax.swing.JButton();
        jBUpdateCompany = new javax.swing.JButton();
        jBDeleteCompany = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        UpdateCompany = new javax.swing.JFrame();
        jPanel12 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jBBackUpdateCompany = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        UpdateCompanyNames = new java.awt.Choice();
        jTUpdateContact = new javax.swing.JTextField();
        jBUpdateContact = new javax.swing.JButton();
        jTUpdateEmail = new javax.swing.JTextField();
        jBUpdateEmail = new javax.swing.JButton();
        desktopPane = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jBExit = new javax.swing.JButton();
        jTUserName = new javax.swing.JTextField();
        jLUserName = new javax.swing.JLabel();
        jLPassWord = new javax.swing.JLabel();
        jTPassWord = new javax.swing.JPasswordField();
        jBSignIn = new javax.swing.JButton();
        jBClear = new javax.swing.JButton();
        image = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(17, 179, 237));

        jBMedicine.setBackground(new java.awt.Color(204, 204, 204));
        jBMedicine.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBMedicine.setText("Medicines");
        jBMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMedicineActionPerformed(evt);
            }
        });

        jBCompanies.setBackground(new java.awt.Color(204, 204, 204));
        jBCompanies.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBCompanies.setText("Companies");
        jBCompanies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCompaniesActionPerformed(evt);
            }
        });

        jBSalesRecords.setBackground(new java.awt.Color(204, 204, 204));
        jBSalesRecords.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBSalesRecords.setText("View Sales Record");

        jBNewSales.setBackground(new java.awt.Color(204, 204, 204));
        jBNewSales.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBNewSales.setText("New Sales");
        jBNewSales.setFocusable(false);
        jBNewSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNewSalesActionPerformed(evt);
            }
        });

        jBChangePassword.setBackground(new java.awt.Color(204, 204, 204));
        jBChangePassword.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBChangePassword.setText("Change Password");
        jBChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBChangePasswordActionPerformed(evt);
            }
        });

        jBLogOut.setBackground(new java.awt.Color(204, 204, 204));
        jBLogOut.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBLogOut.setText("Log Out");
        jBLogOut.setToolTipText("");
        jBLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLogOutActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product Id", "Product Name", "Company Name", "Product Category", "Quantity", "Price Per Unit"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        jBSearch.setBackground(new java.awt.Color(204, 204, 204));
        jBSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBSearch.setText("Search");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("You are Logged in as");

        jlNameLog.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBChangePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBNewSales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBSalesRecords, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                            .addComponent(jBCompanies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBMedicine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 966, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlNameLog, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBSearch))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlNameLog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(200, 200, 200)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBMedicine)
                        .addGap(18, 18, 18)
                        .addComponent(jBCompanies)
                        .addGap(18, 18, 18)
                        .addComponent(jBSalesRecords)
                        .addGap(18, 18, 18)
                        .addComponent(jBNewSales)
                        .addGap(18, 18, 18)
                        .addComponent(jBChangePassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBLogOut))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1.getContentPane());
        Panel1.getContentPane().setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(17, 179, 237));

        jBBackMedicinePanel.setBackground(new java.awt.Color(204, 204, 204));
        jBBackMedicinePanel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBBackMedicinePanel.setText("Back");
        jBBackMedicinePanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBackMedicinePanelActionPerformed(evt);
            }
        });

        jBIMedicine.setBackground(new java.awt.Color(204, 204, 204));
        jBIMedicine.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBIMedicine.setText("Insert Medicine");
        jBIMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIMedicineActionPerformed(evt);
            }
        });

        jBUpdateMedicine.setBackground(new java.awt.Color(204, 204, 204));
        jBUpdateMedicine.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBUpdateMedicine.setText("Update Medicine");
        jBUpdateMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUpdateMedicineActionPerformed(evt);
            }
        });

        jBDeleteMedicine.setBackground(new java.awt.Color(204, 204, 204));
        jBDeleteMedicine.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBDeleteMedicine.setText("Delete Medicine");
        jBDeleteMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDeleteMedicineActionPerformed(evt);
            }
        });

        tblDeleteTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product Id", "Product Name", "Company Name", "Product Category", "Quantity", "Price Per Unit"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblDeleteTable);
        if (tblDeleteTable.getColumnModel().getColumnCount() > 0) {
            tblDeleteTable.getColumnModel().getColumn(0).setResizable(false);
            tblDeleteTable.getColumnModel().getColumn(1).setResizable(false);
            tblDeleteTable.getColumnModel().getColumn(2).setResizable(false);
            tblDeleteTable.getColumnModel().getColumn(3).setResizable(false);
            tblDeleteTable.getColumnModel().getColumn(4).setResizable(false);
            tblDeleteTable.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBBackMedicinePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBIMedicine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBUpdateMedicine, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                    .addComponent(jBDeleteMedicine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 983, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jBIMedicine)
                        .addGap(42, 42, 42)
                        .addComponent(jBUpdateMedicine)
                        .addGap(43, 43, 43)
                        .addComponent(jBDeleteMedicine))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBBackMedicinePanel)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout MedicinePanelLayout = new javax.swing.GroupLayout(MedicinePanel.getContentPane());
        MedicinePanel.getContentPane().setLayout(MedicinePanelLayout);
        MedicinePanelLayout.setHorizontalGroup(
            MedicinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        MedicinePanelLayout.setVerticalGroup(
            MedicinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("     Invalid User name or Password");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout INVALIDINPUTLayout = new javax.swing.GroupLayout(INVALIDINPUT.getContentPane());
        INVALIDINPUT.getContentPane().setLayout(INVALIDINPUTLayout);
        INVALIDINPUTLayout.setHorizontalGroup(
            INVALIDINPUTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        INVALIDINPUTLayout.setVerticalGroup(
            INVALIDINPUTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel6.setBackground(new java.awt.Color(17, 179, 237));

        jBMedicineInputBack.setBackground(new java.awt.Color(204, 204, 204));
        jBMedicineInputBack.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBMedicineInputBack.setText("Back");
        jBMedicineInputBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMedicineInputBackActionPerformed(evt);
            }
        });

        jBMedicineInputInsert.setBackground(new java.awt.Color(204, 204, 204));
        jBMedicineInputInsert.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBMedicineInputInsert.setText("Insert");
        jBMedicineInputInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMedicineInputInsertActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Product Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Company Name");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Product Category");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Product Quantity");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Product Price");

        jTProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTProductNameActionPerformed(evt);
            }
        });

        jTProductQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTProductQuantityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jBMedicineInputBack, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBMedicineInputInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(167, 167, 167)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTProductName)
                                    .addComponent(CompanyChioce, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                                .addComponent(jTProductQuantity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(614, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(CompanyChioce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(ProductChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTProductQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(268, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBMedicineInputInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBMedicineInputBack, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        CompanyChioce.add("GSK");
        CompanyChioce.add("Abbot");
        CompanyChioce.add("Pfizer");
        ProductChoice.add("Tablet");
        ProductChoice.add("Syrup");
        ProductChoice.add("Cream");

        javax.swing.GroupLayout MedicineInputLayout = new javax.swing.GroupLayout(MedicineInput.getContentPane());
        MedicineInput.getContentPane().setLayout(MedicineInputLayout);
        MedicineInputLayout.setHorizontalGroup(
            MedicineInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MedicineInputLayout.setVerticalGroup(
            MedicineInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(17, 179, 237));

        jBBackUpdateMedicine.setBackground(new java.awt.Color(204, 204, 204));
        jBBackUpdateMedicine.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBBackUpdateMedicine.setText("Back");
        jBBackUpdateMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBackUpdateMedicineActionPerformed(evt);
            }
        });

        tblUpdateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product Id", "Product Name", "Company Name", "Product Category", "Quantity", "Price Per Unit"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblUpdateTable);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("PRODUCT NAME");

        jTUpdatePrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jBUpdatePrice.setBackground(new java.awt.Color(204, 204, 204));
        jBUpdatePrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBUpdatePrice.setText("Update Price");
        jBUpdatePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUpdatePriceActionPerformed(evt);
            }
        });

        jTUpdateQuantity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jBUpdateQuantity.setBackground(new java.awt.Color(204, 204, 204));
        jBUpdateQuantity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBUpdateQuantity.setText("Update Quantity");
        jBUpdateQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUpdateQuantityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jBBackUpdateMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(709, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTUpdateQuantity)
                            .addComponent(jTUpdatePrice)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(UpdateMedicineNames, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jBUpdatePrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBUpdateQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))))
                        .addGap(333, 333, 333))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(UpdateMedicineNames, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(46, 46, 46)
                                .addComponent(jTUpdatePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jBUpdatePrice))
                        .addGap(88, 88, 88))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBUpdateQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTUpdateQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jBBackUpdateMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        DatabaseManager dbm=new DatabaseManager();
        ArrayList <Medicine> meds=dbm.getAllMedicines();
        for(Medicine m : meds)
        {
            UpdateMedicineNames.add(m.getName());
        }

        javax.swing.GroupLayout UpdateMedicinePanelLayout = new javax.swing.GroupLayout(UpdateMedicinePanel.getContentPane());
        UpdateMedicinePanel.getContentPane().setLayout(UpdateMedicinePanelLayout);
        UpdateMedicinePanelLayout.setHorizontalGroup(
            UpdateMedicinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        UpdateMedicinePanelLayout.setVerticalGroup(
            UpdateMedicinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(17, 179, 237));

        jBCompanyInputBack.setBackground(new java.awt.Color(204, 204, 204));
        jBCompanyInputBack.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBCompanyInputBack.setText("Back");
        jBCompanyInputBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCompanyInputBackActionPerformed(evt);
            }
        });

        jBCompanyInputInsert.setBackground(new java.awt.Color(204, 204, 204));
        jBCompanyInputInsert.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBCompanyInputInsert.setText("Insert");
        jBCompanyInputInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCompanyInputInsertActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Company Name");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Company Country");
        jLabel14.setToolTipText("");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Company Email");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Comapny Address");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Company Conatact no.");

        jTComapnyAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTComapnyAddressActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jBCompanyInputBack, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCompanyInputInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(157, 157, 157)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTCompanyName, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jTComapnyAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jTComapnyContact, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(JTCompanyCountry)
                            .addComponent(jTCompanyEmail)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(570, 570, 570))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jTCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(JTCompanyCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTCompanyEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTComapnyContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTComapnyAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(264, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCompanyInputInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCompanyInputBack, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout InsertCompanyLayout = new javax.swing.GroupLayout(InsertCompany.getContentPane());
        InsertCompany.getContentPane().setLayout(InsertCompanyLayout);
        InsertCompanyLayout.setHorizontalGroup(
            InsertCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        InsertCompanyLayout.setVerticalGroup(
            InsertCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel11.setBackground(new java.awt.Color(17, 179, 237));

        jBBackCompanyPanel.setBackground(new java.awt.Color(204, 204, 204));
        jBBackCompanyPanel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBBackCompanyPanel.setText("Back");
        jBBackCompanyPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBackCompanyPanelActionPerformed(evt);
            }
        });

        jBInsertCompany.setBackground(new java.awt.Color(204, 204, 204));
        jBInsertCompany.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBInsertCompany.setText("Insert Company");
        jBInsertCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInsertCompanyActionPerformed(evt);
            }
        });

        jBUpdateCompany.setBackground(new java.awt.Color(204, 204, 204));
        jBUpdateCompany.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBUpdateCompany.setText("Update Company");
        jBUpdateCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUpdateCompanyActionPerformed(evt);
            }
        });

        jBDeleteCompany.setBackground(new java.awt.Color(204, 204, 204));
        jBDeleteCompany.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBDeleteCompany.setText("Delete Company");
        jBDeleteCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDeleteCompanyActionPerformed(evt);
            }
        });

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product Id", "Product Name", "Company Name", "Product Category", "Quantity", "Price Per Unit"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jTable7);
        if (jTable7.getColumnModel().getColumnCount() > 0) {
            jTable7.getColumnModel().getColumn(0).setResizable(false);
            jTable7.getColumnModel().getColumn(1).setResizable(false);
            jTable7.getColumnModel().getColumn(2).setResizable(false);
            jTable7.getColumnModel().getColumn(3).setResizable(false);
            jTable7.getColumnModel().getColumn(4).setResizable(false);
            jTable7.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBBackCompanyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBInsertCompany, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBUpdateCompany, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                    .addComponent(jBDeleteCompany, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 983, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jBInsertCompany)
                        .addGap(42, 42, 42)
                        .addComponent(jBUpdateCompany)
                        .addGap(43, 43, 43)
                        .addComponent(jBDeleteCompany))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBBackCompanyPanel)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout ComapnyPanelLayout = new javax.swing.GroupLayout(ComapnyPanel.getContentPane());
        ComapnyPanel.getContentPane().setLayout(ComapnyPanelLayout);
        ComapnyPanelLayout.setHorizontalGroup(
            ComapnyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        ComapnyPanelLayout.setVerticalGroup(
            ComapnyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel12.setBackground(new java.awt.Color(17, 179, 237));

        jBBackUpdateCompany.setBackground(new java.awt.Color(204, 204, 204));
        jBBackUpdateCompany.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBBackUpdateCompany.setText("Back");
        jBBackUpdateCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBackUpdateCompanyActionPerformed(evt);
            }
        });

        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product Id", "Product Name", "Company Name", "Product Category", "Quantity", "Price Per Unit"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane8.setViewportView(jTable8);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("COMPANY NAME");

        jTUpdateContact.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jBUpdateContact.setBackground(new java.awt.Color(204, 204, 204));
        jBUpdateContact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBUpdateContact.setText("Update Contact");

        jTUpdateEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jBUpdateEmail.setBackground(new java.awt.Color(204, 204, 204));
        jBUpdateEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBUpdateEmail.setText("Update Quantity");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jBBackUpdateCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(709, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTUpdateEmail)
                            .addComponent(jTUpdateContact)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(UpdateCompanyNames, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jBUpdateContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBUpdateEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))))
                        .addGap(333, 333, 333))))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(UpdateCompanyNames, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(46, 46, 46)
                                .addComponent(jTUpdateContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jBUpdateContact))
                        .addGap(88, 88, 88))
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBUpdateEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTUpdateEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jBBackUpdateCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout UpdateCompanyLayout = new javax.swing.GroupLayout(UpdateCompany.getContentPane());
        UpdateCompany.getContentPane().setLayout(UpdateCompanyLayout);
        UpdateCompanyLayout.setHorizontalGroup(
            UpdateCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        UpdateCompanyLayout.setVerticalGroup(
            UpdateCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(17, 179, 237));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jBExit.setBackground(new java.awt.Color(102, 102, 102));
        jBExit.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jBExit.setText("EXIT");
        jBExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExitActionPerformed(evt);
            }
        });

        jTUserName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLUserName.setBackground(new java.awt.Color(0, 153, 204));
        jLUserName.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLUserName.setForeground(new java.awt.Color(255, 255, 255));
        jLUserName.setText("UserName:");

        jLPassWord.setBackground(new java.awt.Color(0, 153, 204));
        jLPassWord.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLPassWord.setForeground(new java.awt.Color(255, 255, 255));
        jLPassWord.setText("PassWord:");

        jTPassWord.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jBSignIn.setBackground(new java.awt.Color(0, 153, 204));
        jBSignIn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBSignIn.setForeground(new java.awt.Color(255, 255, 255));
        jBSignIn.setText("Sign in");
        jBSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSignInActionPerformed(evt);
            }
        });

        jBClear.setBackground(new java.awt.Color(0, 153, 204));
        jBClear.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBClear.setForeground(new java.awt.Color(255, 255, 255));
        jBClear.setText("Clear");
        jBClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBClearActionPerformed(evt);
            }
        });

        image.setBackground(new java.awt.Color(255, 255, 255));
        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(422, 422, 422)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jBSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(jBClear, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTPassWord, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                                .addComponent(jLUserName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTUserName, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jBExit, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1371, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jTPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBSignIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(229, 229, 229)
                .addComponent(jBExit, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        desktopPane.setLayer(jPanel2, javax.swing.JLayeredPane.POPUP_LAYER);

        getContentPane().add(desktopPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBExitActionPerformed

    private void jBSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSignInActionPerformed
        // TODO add your handling code here:
        User user=new User(jTUserName.getText(),jTPassWord.getText());
        if (valid.containsUser(user)) {
            if(user.getType().equals("administrator"))
            {
                setScreenSize(MedicinePanel);
                ArrayList <Medicine> list=dbm.getAllMedicines();
                initDeleteTable();
                for(Medicine m : list)
                {
                    deleteTableModel.addRow(new Object[]{Integer.toString(m.getId()), m.getName(), m.getCompany(), m.getType(), Integer.toString(m.getQuantity()), Integer.toString(m.getPrice())});
                }
                tblDeleteTable.setModel(deleteTableModel);
            }
            else if(user.getType().equals("customer"))
            {
                setScreenSize(Panel1);
            }
            jlNameLog.setText(jTUserName.getText());
            this.dispose();
        } else
        {
//            INVALIDINPUT.setAlwaysOnTop(true);
//            INVALIDINPUT.setVisible(true);
//            INVALIDINPUT.setLocation(800, 300);
        }
    }//GEN-LAST:event_jBSignInActionPerformed

    private void jBClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBClearActionPerformed
        // TODO add your handling code here:
        jTUserName.setText("");
        jTPassWord.setText("");
    }//GEN-LAST:event_jBClearActionPerformed

    private void jBMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMedicineActionPerformed
        // TODO add your handling code here:
        setScreenSize(MedicinePanel);
        Panel1.dispose();
    }//GEN-LAST:event_jBMedicineActionPerformed

    private void jBLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLogOutActionPerformed
        // TODO add your handling code here:
        Panel1.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_jBLogOutActionPerformed

    private void jBChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBChangePasswordActionPerformed
        // TODO add your handling code here:
        dbm.updateUser(new User(jTUserName.getText(), jTPassWord.getText()));
    }//GEN-LAST:event_jBChangePasswordActionPerformed

    private void jBBackMedicinePanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBackMedicinePanelActionPerformed
        // TODO add your handling code here:
        MedicinePanel.dispose();
        Panel1.setVisible(true);
    }//GEN-LAST:event_jBBackMedicinePanelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        INVALIDINPUT.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBIMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIMedicineActionPerformed
        // TODO add your handling code here:
        setScreenSize(MedicineInput);
        this.dispose();
    }//GEN-LAST:event_jBIMedicineActionPerformed

    private void jBMedicineInputBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMedicineInputBackActionPerformed
        // TODO add your handling code here:
        MedicineInput.dispose();
        MedicinePanel.setVisible(true);
    }//GEN-LAST:event_jBMedicineInputBackActionPerformed

    private void jTProductQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTProductQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTProductQuantityActionPerformed

    private void jBBackUpdateMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBackUpdateMedicineActionPerformed
        // TODO add your handling code here:
        UpdateMedicinePanel.dispose();
        tblDeleteTable.setModel(updateTableModel);
        MedicinePanel.setVisible(true);
    }//GEN-LAST:event_jBBackUpdateMedicineActionPerformed

    private void jBUpdateMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUpdateMedicineActionPerformed
        // TODO add your handling code here:
        
        setScreenSize(UpdateMedicinePanel);
        MedicinePanel.dispose();
        initUpdateTable();
        ArrayList <Medicine> list=dbm.getAllMedicines();
        for(Medicine m : list)
        {
            updateTableModel.addRow(new Object[]{m.getId(), m.getName(), m.getCompany(), m.getType(), Integer.toString(m.getQuantity()), Integer.toString(m.getPrice())});
        }
        tblUpdateTable.setModel(updateTableModel);
    }//GEN-LAST:event_jBUpdateMedicineActionPerformed

    private void jBDeleteMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeleteMedicineActionPerformed
        try {
            // TODO add your handling code here:
            int row=tblDeleteTable.getSelectedRow();
            if(row!=-1)
            {
                Medicine m=items.getItem(row);
                dbm.deleteMedicine(m.getId());
                deleteTableModel.removeRow(row);
                tblDeleteTable.setModel(deleteTableModel);
            }
        } catch (SQLException ex) {
            Logger.getLogger(MedicalStore.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBDeleteMedicineActionPerformed

    private void jBCompanyInputBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCompanyInputBackActionPerformed
        // TODO add your handling code here:
        InsertCompany.dispose();
        ComapnyPanel.setVisible(true);
        
    }//GEN-LAST:event_jBCompanyInputBackActionPerformed

    private void jTComapnyAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTComapnyAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTComapnyAddressActionPerformed

    private void jBBackCompanyPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBackCompanyPanelActionPerformed
        // TODO add your handling code here:
        ComapnyPanel.dispose();
        Panel1.setVisible(true);
    }//GEN-LAST:event_jBBackCompanyPanelActionPerformed

    private void jBInsertCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInsertCompanyActionPerformed
        // TODO add your handling code here:
        setScreenSize(InsertCompany);
        ComapnyPanel.dispose();
    }//GEN-LAST:event_jBInsertCompanyActionPerformed

    private void jBUpdateCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUpdateCompanyActionPerformed
        // TODO add your handling code here:
        setScreenSize(UpdateCompany);
        ComapnyPanel.dispose();
    }//GEN-LAST:event_jBUpdateCompanyActionPerformed

    private void jBDeleteCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeleteCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBDeleteCompanyActionPerformed

    private void jBCompaniesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCompaniesActionPerformed
        // TODO add your handling code here:
        setScreenSize(ComapnyPanel);
        Panel1.dispose();
    }//GEN-LAST:event_jBCompaniesActionPerformed

    private void jBBackUpdateCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBackUpdateCompanyActionPerformed
        // TODO add your handling code here:
        UpdateCompany.dispose();
        ComapnyPanel.setVisible(true);
    }//GEN-LAST:event_jBBackUpdateCompanyActionPerformed

    private void jTProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTProductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTProductNameActionPerformed

    private void jBMedicineInputInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMedicineInputInsertActionPerformed
        // TODO add your handling code here:
        if(valid.isNumber(jTProductQuantity.getText()) && valid.isNumber(jTProductPrice.getText()) && !valid.containsMedicine(new Medicine(jTProductName.getText(), Integer.parseInt(jTProductQuantity.getText()), CompanyChioce.getSelectedItem(), Integer.parseInt(jTProductPrice.getText()), ProductChoice.getSelectedItem())))
        {
            dbm.insertMedicine(new Medicine(jTProductName.getText(), Integer.parseInt(jTProductQuantity.getText()), CompanyChioce.getSelectedItem(), Integer.parseInt(jTProductPrice.getText()), ProductChoice.getSelectedItem()));
            Medicine m=dbm.searchMedicine(jTProductName.getText());
            deleteTableModel.addRow(new Object[]{Integer.toString(m.getId()), m.getName(), m.getCompany(), m.getType(), Integer.toString(m.getQuantity()), Integer.toString(m.getPrice())});
            tblDeleteTable.setModel(deleteTableModel);
        }
        
    }//GEN-LAST:event_jBMedicineInputInsertActionPerformed

    private void jBNewSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNewSalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBNewSalesActionPerformed

    private void jBUpdatePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUpdatePriceActionPerformed
        // TODO add your handling code here:
        if(valid.isNumber(jTUpdatePrice.getText()))
        {
            dbm.updateMedicinePrice(UpdateMedicineNames.getSelectedItem(), Integer.parseInt(jTUpdatePrice.getText()));
            initUpdateTable();
            ArrayList <Medicine> list=dbm.getAllMedicines();
            for(Medicine m : list)
            {
                updateTableModel.addRow(new Object[]{m.getId(), m.getName(), m.getCompany(), m.getType(), Integer.toString(m.getQuantity()), Integer.toString(m.getPrice())});
            }
            tblUpdateTable.setModel(updateTableModel);
        }
    }//GEN-LAST:event_jBUpdatePriceActionPerformed

    private void jBUpdateQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUpdateQuantityActionPerformed
        // TODO add your handling code here:
        if(valid.isNumber(jTUpdateQuantity.getText()))
        {
            dbm.updateMedicineQuantity(UpdateMedicineNames.getSelectedItem(), Integer.parseInt(jTUpdateQuantity.getText()));
            initUpdateTable();
            ArrayList <Medicine> list=dbm.getAllMedicines();
            for(Medicine m : list)
            {
                updateTableModel.addRow(new Object[]{m.getId(), m.getName(), m.getCompany(), m.getType(), Integer.toString(m.getQuantity()), Integer.toString(m.getPrice())});
            }
            tblUpdateTable.setModel(updateTableModel);
        }
    }//GEN-LAST:event_jBUpdateQuantityActionPerformed

    private void jBCompanyInputInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCompanyInputInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBCompanyInputInsertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicalStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicalStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicalStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicalStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedicalStore().setVisible(true);
            }
        });
    }
    public void setScreenSize(JFrame jfr)
    {
        jfr.setUndecorated(true);
        Toolkit tk = Toolkit.getDefaultToolkit();//this get the sizes of screen
        int xsize = (int) tk.getScreenSize().getWidth();//taking the width of screen
        int ysize = (int) tk.getScreenSize().getHeight();//taking the height of screen
        jfr.setSize(xsize, ysize);
        jfr.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame ComapnyPanel;
    private java.awt.Choice CompanyChioce;
    private javax.swing.JFrame INVALIDINPUT;
    private javax.swing.JFrame InsertCompany;
    private javax.swing.JTextField JTCompanyCountry;
    private javax.swing.JFrame MedicineInput;
    private javax.swing.JFrame MedicinePanel;
    private javax.swing.JFrame Panel1;
    private java.awt.Choice ProductChoice;
    private javax.swing.JFrame UpdateCompany;
    private java.awt.Choice UpdateCompanyNames;
    private java.awt.Choice UpdateMedicineNames;
    private javax.swing.JFrame UpdateMedicinePanel;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel image;
    private javax.swing.JButton jBBackCompanyPanel;
    private javax.swing.JButton jBBackMedicinePanel;
    private javax.swing.JButton jBBackUpdateCompany;
    private javax.swing.JButton jBBackUpdateMedicine;
    private javax.swing.JButton jBChangePassword;
    private javax.swing.JButton jBClear;
    private javax.swing.JButton jBCompanies;
    private javax.swing.JButton jBCompanyInputBack;
    private javax.swing.JButton jBCompanyInputInsert;
    private javax.swing.JButton jBDeleteCompany;
    private javax.swing.JButton jBDeleteMedicine;
    private javax.swing.JButton jBExit;
    private javax.swing.JButton jBIMedicine;
    private javax.swing.JButton jBInsertCompany;
    private javax.swing.JButton jBLogOut;
    private javax.swing.JButton jBMedicine;
    private javax.swing.JButton jBMedicineInputBack;
    private javax.swing.JButton jBMedicineInputInsert;
    private javax.swing.JButton jBNewSales;
    private javax.swing.JButton jBSalesRecords;
    private javax.swing.JButton jBSearch;
    private javax.swing.JButton jBSignIn;
    private javax.swing.JButton jBUpdateCompany;
    private javax.swing.JButton jBUpdateContact;
    private javax.swing.JButton jBUpdateEmail;
    private javax.swing.JButton jBUpdateMedicine;
    private javax.swing.JButton jBUpdatePrice;
    private javax.swing.JButton jBUpdateQuantity;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLPassWord;
    private javax.swing.JLabel jLUserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextField jTComapnyAddress;
    private javax.swing.JTextField jTComapnyContact;
    private javax.swing.JTextField jTCompanyEmail;
    private javax.swing.JTextField jTCompanyName;
    private javax.swing.JPasswordField jTPassWord;
    private javax.swing.JTextField jTProductName;
    private javax.swing.JTextField jTProductPrice;
    private javax.swing.JTextField jTProductQuantity;
    private javax.swing.JTextField jTSearch;
    private javax.swing.JTextField jTUpdateContact;
    private javax.swing.JTextField jTUpdateEmail;
    private javax.swing.JTextField jTUpdatePrice;
    private javax.swing.JTextField jTUpdateQuantity;
    private javax.swing.JTextField jTUserName;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable7;
    private javax.swing.JTable jTable8;
    private javax.swing.JLabel jlNameLog;
    private javax.swing.JTable tblDeleteTable;
    private javax.swing.JTable tblUpdateTable;
    // End of variables declaration//GEN-END:variables

}
